application:
  debug: !env DEBUG
  project: "CodeQuill"
  contact_email: "info@ophelios.com"
  version: "0.0.0"
  locales:
    - en_CA

locale:
  currency: "CAD"
  timezone: "America/Montreal"
  charset: "utf8"
  locale: "en_CA"

mailer:
  transport: !env MAILER_TRANSPORT
  default_from_address: "info@ophelios.com"
  default_from_name: "CodeQuill"
  aws:
    api_key: !env AWS_KEY
    api_secret: !env AWS_SECRET
  smtp:
    enabled: true
    host: "localhost"
    port: 1025
    encryption: "none"
    username: ""
    password: ""

database:
  hostname: !env DB_HOSTNAME
  username: !env DB_USERNAME
  password: !env DB_PASSWORD
  database: !env DB_NAME
  search_paths:
    - public

render:
  engine: "latte"
  cache_update: !env CACHE_UPDATE

session:
  storage: "database"
  table: "public.session"
  encrypted: false
  lifetime: 28800
  auto_start: true

services:
  mint:
    private_key: !env NFT_MINT_PRIVATE
    contract_address: !env NFT_MINT_ADDRESS

  infura:
    eth_url: !env INFURA_ETH_URL
    polygon_url: !env INFURA_POLYGON_URL

  tusky:
    api_key: !env TUSKY_API_KEY

  moralis:
    api_key: !env MORALIS_API_KEY

  github:
    client_id: !env GITHUB_CLIENT_ID
    client_secret: !env GITHUB_CLIENT_SECRET
    callback: "/oauth/github/callback"

  aws:
    region: 'ca-central-1'
    version: 'latest'
    api_key: !env AWS_KEY
    api_secret: !env AWS_SECRET

security:
  pwned:
    enabled: true
    tolerance: 1
  password:
    pepper: !env PASSWORD_PEPPER
  encryption:
    key: !env ENCRYPTION_KEY
  csrf:
    enabled: true
    exceptions: ['\/app\/api.*']
  ids:
    enabled: true
    impact_threshold: 50

