<?php namespace Controllers\Application\Profile;

use Controllers\Application\AppController;
use Pulsar\Account\Passport;
use Pulsar\OAuth\GitHub\GitHubService;
use Zephyrus\Network\Response;
use Zephyrus\Network\Router\Root;

#[Root("/app/profile")]
abstract class ProfileController extends AppController
{
    public function render(string $page, array $args = []): Response
    {
        $user = null;
        if (Passport::getUser()->authentication->oauth_provider) {
            $user = new GitHubService(Passport::getUser()->authentication->oauth_access_token)->getUser();
        }
        $args = array_merge($args, [
            'github_user' => $user
        ]);
        return parent::render($page, $args); // TODO: Change the autogenerated stub
    }

}
