name: Deploy to Production 🚀

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'production'
      config_file: 'fly_prod.toml'
    secrets: inherit
