name: Deploy 🚀

on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        type: string
      config_file:
        description: 'Fly configuration file to use'
        required: true
        type: string
    secrets:
      FLY_API_TOKEN:
        required: true
        description: 'Fly.io API token for deployment'

jobs:
  deploy:
    name: Deploy to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Fly actions
        uses: superfly/flyctl-actions/setup-flyctl@1.5

      - name: Deploy to Fly.io
        run: flyctl deploy --config _deploy/${{ inputs.config_file }} --dockerfile _deploy/Dockerfile --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
